### ISSUE TITLE
No modo 'robot' usar massa como critério de desempate.

### ISSUE THREAD

**Issue by dpasqualin** [dpasqualin/agar.io-clone#19]
Quando dois jogadores tiverem a mesma quantidade de pontos a massa deve ser usada para desempate.

**Comment by CristianWeiland** [comment]
Isso não foi implementado ainda? Aparentemente a função de ordenação de scores compara primeiramente por pontos e depois por massa (na função sortUsersByPoints).

scores.sort( function(a, b) {
    if(a.points != b.points) {
        return b.points - a.points;
    } else {
        return b.mass - a.mass;
    }
});

**Comment by dpasqualin** [comment]
Foi. Pode fechar por favor :P

Em 13/08/2016 11:44, "CristianWeiland" notifications@github.com escreveu:
