### ISSUE TITLE
Descrever como as células se juntam novamente

### ISSUE THREAD

**Issue by dpasqualin** [dpasqualin/agar.io-clone#3]
Não encontrei a parte do código que calcula quando as células que foram separadas se juntam novamente. Gostaria que isso fosse um parâmetro do programa em config.json

**Comment by CristianWeiland** [comment]
Isso já é um parâmetro em config.json. O parâmetro é mergeTimer (cujo default é 15). Ele é dado em segundos.
O cálculo no código se dá na função movePlayer, que multiplica esse valor por 1000 (transformando-o em milissegundos) e subtraindo-o do timestamp atual.
